// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfhjB-l1WEcBX2kPuFg8peIohjeDqYIW8',
    appId: '1:345282023143:web:9a58d67faa706c9c021c42',
    messagingSenderId: '345282023143',
    projectId: 'carfilo',
    authDomain: 'carfilo.firebaseapp.com',
    databaseURL:
        'https://carfilo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carfilo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ0lztvLm3qYu5_iAiPkqczewXhjY-Yow',
    appId: '1:345282023143:android:b6dd8c03f5301936021c42',
    messagingSenderId: '345282023143',
    projectId: 'carfilo',
    databaseURL:
        'https://carfilo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carfilo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDFrUyIcdXNMXbUlQ0NHQYd0kWpCFAnR8',
    appId: '1:345282023143:ios:6f381b7a5da92471021c42',
    messagingSenderId: '345282023143',
    projectId: 'carfilo',
    databaseURL:
        'https://carfilo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carfilo.appspot.com',
    iosBundleId: 'com.example.filomBakim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDFrUyIcdXNMXbUlQ0NHQYd0kWpCFAnR8',
    appId: '1:345282023143:ios:a1ae61d98f1066b9021c42',
    messagingSenderId: '345282023143',
    projectId: 'carfilo',
    databaseURL:
        'https://carfilo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carfilo.appspot.com',
    iosBundleId: 'com.example.filomBakim.RunnerTests',
  );
}
